### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by AirLeMineral** [MintoD/MoneyPool#1]
ParseError: "syntax error, unexpected 'Config' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)" (EXCEPTION) in "plugins/MoneyPool.phar/src/MintoD/MoneyPool/Main" at line 19

**Comment by MintoD** [comment]
Sorry for your slow reply. Thanks for reporting me. It has been fixed

**Comment by AirLeMineral** [comment]
> Sorry for your slow reply. Thanks for reporting me. It has been fixed

 Error: "Class 'MintoD\BedrockUnicodeCharacters\BedrockUnicodeCharacters' not found" (EXCEPTION) in "plugins/MoneyPool-main/src/MintoD/MoneyPool/Main" at line 53

**Comment by AirLeMineral** [comment]
Error: "Call to a member function getTaskId() on null" (EXCEPTION) in "plugins/MoneyPool-main/src/MintoD/MoneyPool/Main" at line 33

**Comment by MintoD** [comment]
Thanks, I fixed it! Enjoy

**Comment by AirLeMineral** [comment]
> Thanks, I fixed it! Enjoy

command /moneypool not found

**Comment by MintoD** [comment]
You must be OP are use PurePerms
